jwt:
  prefix: Bearer
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437


spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path= /users/**
          filters:
#            - RoleAuth=ADMIN,USER
            - AuthenticationFilter

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path= /hotel/**
          filters:
            - AuthenticationFilter


        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path= /rating/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /auth/**
          filters:
            - AuthenticationFilter


  application:
       name: APIGateWay

server:
   port: 8083

eureka:
  instance:
     prefer-ip-address: true
  client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
           defaultZone: http://localhost:8761/eureka